version: '3'
volumes:
  bundle:
  psql-data:
services:
  app:
    build: .
    ports:
      - 3000:3000 # rails server
      - 3035:3035 # webpack-dev-server
    volumes:
      - bundle:/usr/local/bundle:cached
      - .:/app:delegated
      # ホスト <-> ゲスト間で同期する必要がないファイルを明示的に指定し、同期速度を上げる
      - /app/.git
      - /app/.github
      - /app/log
      - /app/node_modules
      - /app/public/packs
      - /app/public/packs-test
      - /app/public/assets
      - /app/tmp
      - /app/vendor
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    stdin_open: true
    tty: true
    command: /bin/sh docker-start.sh

  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
    - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
